### ISSUE TITLE
Clean up/finalize baseline LSTM

### ISSUE THREAD

**Issue by lekoenig** [USGS-R/drb-do-ml#159]
This issue captures several tasks that are needed to clean up/finalize the baseline LSTM:

- [x] Add `tmmn` to list of meteorological drivers #153
- [x] Check date formatting for gridmet data
- [ ] Incorporate gridmet data in targets pipeline #151 
- [x] Add additional segment/catchment attributes at NHDPlusv2-scale #51
- [x] `inputs_and_outputs_med_obs` in `2a_model.R` has redundant COMID columns
- [x] Simplify pipeline by omitting targets for _both_ well-observed and medium-observed sites #148 
- [x] Decide whether provisional data will be included in the observations used for model training #135 
- [x] Val times are currently defined in two places, and the values differ between those locations #160 
- [ ] Flesh out README to describe the modeling inputs and steps, including how to modify and run the model #146
